name: confreelander
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  characters: ^1.2.1
  collection: '>=1.16.0'
  benchmark_harness: any
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
